### ISSUE TITLE
公众菜单号点击生效报错(v0.4.1_for10)

### ISSUE THREAD

**Issue by siyuancn** [JoneXiong/oejia_wx#12]
Traceback (most recent call last):
  File "/opt/odoo/sources/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/sources/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/sources/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/sources/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/sources/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/sources/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/sources/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/sources/odoo/addons/web/controllers/main.py", line 1129, in run
    result = request.env['ir.actions.server'].browse([action_id]).run()
  File "/opt/odoo/sources/odoo/odoo/addons/base/ir/ir_actions.py", line 972, in run
    res = func(action, eval_context=eval_context)
  File "/opt/odoo/sources/odoo/odoo/addons/base/ir/ir_actions.py", line 795, in run_action_code_multi
    safe_eval(action.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/opt/odoo/sources/odoo/odoo/tools/safe_eval.py", line 301, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
ValueError: <type 'exceptions.NameError'>: "name 'self' is not defined" while evaluating
u"self.do_active(cr, uid, context.get('active_ids', []), context=context)"

**Comment by 1806933** [comment]
我也有同样的问题

**Comment by JoneXiong** [comment]
已修复  见v0.4.2_for10  odoo版本写法兼容问题  self.do_active 改为 records.do_active 即可
