### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by lirux9873** [JoneXiong/oejia_wx#22]
I get the following error, if I try to install the module on odoo12 on CentOS7:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo12/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo12/odoo/tools/convert.py", line 573, in _tag_record
    model = self.env[rec_model]
  File "/opt/odoo/odoo12/odoo/api.py", line 820, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/opt/odoo/odoo12/odoo/modules/registry.py", line 176, in __getitem__
    return self.models[model_name]
KeyError: 'ir.values'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo12/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo12/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo12/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo12/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo12/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo12/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo12/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo12/odoo/http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo12/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo12/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo12/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo12/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo12/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/opt/odoo/odoo12/odoo/addons/base/models/ir_module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo12/odoo/addons/base/models/ir_module.py", line 442, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo12/odoo/addons/base/models/ir_module.py", line 535, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo12/odoo/modules/loading.py", line 426, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo12/odoo/modules/loading.py", line 318, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo12/odoo/modules/loading.py", line 224, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo/odoo12/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo12/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo12/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo12/odoo/tools/convert.py", line 754, in parse
    self.parse(rec, mode)
  File "/opt/odoo/odoo12/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/opt/odoo/odoo12/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo12/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo12/odoo/tools/convert.py", line 573, in _tag_record
    model = self.env[rec_model]
  File "/opt/odoo/odoo12/odoo/api.py", line 820, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/opt/odoo/odoo12/odoo/modules/registry.py", line 176, in __getitem__
    return self.models[model_name]
odoo.tools.convert.ParseError: "ir.values" while parsing /opt/odoo/odoo12-custom-addons/oejia_wx/views/wx_media_views.xml:61, near
<record model="ir.values" id="wx_media_action_server_144_src_value">
            <field name="name">wx_media_action_server_144_src_value</field>
            <field name="action_id" ref="wx_media_action_server_144"/>
            <field name="value" eval="'ir.actions.server,' + str(ref('wx_media_action_server_144'))"/>
            <field name="key">action</field>
            <field name="model">wx.media</field>
            <field name="model_id" ref="model_wx_media"/>
            <field name="key2">client_action_multi</field>
        </record>

**Comment by JoneXiong** [comment]
fixed it  https://github.com/JoneXiong/oejia_wx/commit/bfe23105678328227ff2e91f28d86725051b19e0
@marvin981973 use the latest 12.0 branch
