### ISSUE TITLE
模块加载 oejia_wx 失败: 文件 oejia_wx/security/ir.model.access.csv 无法处理:

### ISSUE THREAD

**Issue by zoyoyo** [JoneXiong/oejia_wx#29]
Odoo 12.0-20190614 (社区版)
软件是这个 https://github.com/JoneXiong/oejia_wx/releases/tag/v0.5.8_for12
依赖的python库：wechatpy、pycrypto 都已装好。
root@odoo:/usr/lib/python3/dist-packages/odoo/addons/oejia_wx# pip install pycrypto
Requirement already satisfied: pycrypto in /usr/lib/python2.7/dist-packages
root@odoo:/usr/lib/python3/dist-packages/odoo/addons/oejia_wx# pip install wechatpy
Requirement already satisfied: wechatpy in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: xmltodict>=0.11.0 in /usr/local/lib/python2.7/dist-packages (from wechatpy)
Requirement already satisfied: enum34>=1.1.4; python_version < "3.4" in /usr/lib/python2.7/dist-packages (from wechatpy)
Requirement already satisfied: optionaldict>=0.1.0 in /usr/local/lib/python2.7/dist-packages (from wechatpy)
Requirement already satisfied: requests>=2.4.3 in /usr/local/lib/python2.7/dist-packages (from wechatpy)
Requirement already satisfied: six>=1.8.0 in /usr/local/lib/python2.7/dist-packages (from wechatpy)
Requirement already satisfied: python-dateutil>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from wechatpy)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=2.4.3->wechatpy)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests>=2.4.3->wechatpy)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests>=2.4.3->wechatpy)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests>=2.4.3->wechatpy)
root@odoo:/usr/lib/python3/dist-packages/odoo/addons/oejia_wx#
看过前面的帖子，也重启过Ubuntu18.04系统，再装的还是报错

安装oejia_wx时报错误如下:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 798, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 845, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: 模块加载 oejia_wx 失败: 文件 oejia_wx/security/ir.model.access.csv 无法处理:
 在字段'Object'中没找到匹配的记录外部 ID 'model_wx_user'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_user_group'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_menu'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_menu_item_base'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_menu_item_left'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_menu_item_middle'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_menu_item_right'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_corpuser'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_config_settings'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_config_corpsettings'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_autoreply'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_articlesreply_article'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_action_act_url'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_action_act_text'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_action_act_custom'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_action_act_article'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_app_config'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_action_act_wxa'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_media'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_action_act_media'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_config_corpsettings'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_config_settings'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_app_config'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_approval_record'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_approval_record'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_articlesreply_article'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_media_article'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_send_mass'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_approval_record'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_config'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_config'
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值

**Comment by zoyoyo** [comment]
我找到原因了。因为我安装的是Python 3.6.8
在安装依赖模块时应该用pip3 命令，而不是pip命令。
所以先安装pip3   apt install python3-pip
再安装依赖模块  pip3 install wechatpy[cryptography]
