### ISSUE TITLE
客户端无法收到odoo端的回复

### ISSUE THREAD

**Issue by alanljj** [JoneXiong/oejia_wx#3]
odoo 8，今天git下来安装成功，同步用户和组成功，添加菜单成功，用户从公众和直接发微信，odoo端可以收到，并自动回复“请稍后，正在分配客服为您解答”，但是odoo端回复后，公众号客户的收到不回复。

log错误：2016-03-24 07:56:01,290 1674 WARNING odoodb openerp.addons.oejia_wx.controllers.routes: No handler responded message <werobot.messages.EventMessage object at 0x7f237f6b5cd0>

**Comment by tangramor** [comment]
类似的问题，日志错误信息：

```
[30/Nov/2016 07:49:14] "POST /corp_handler?msg_signature=9046f7ef800cd14b02dd31de1e456b19eefdc55a&timestamp=1480491833&nonce=1205503047 HTTP/1.0" 500 -
2016-11-30 07:49:14,228 16761 ERROR mengzhicheng_pe werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1297, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1271, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1444, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/addons/crm/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/opt/odoo/addons/website/models/ir_http.py", line 148, in _dispatch
    resp = super(ir_http, self)._dispatch()
  File "/opt/odoo/openerp/addons/base/ir/ir_http.py", line 175, in _dispatch
    return self._handle_exception(e)
  File "/opt/odoo/addons/website/models/ir_http.py", line 196, in _handle_exception
    return super(ir_http, self)._handle_exception(exception)
  File "/opt/odoo/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 673, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/openerp/http.py", line 691, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/myaddons/oejia_wx/controllers/wx_handler.py", line 77, in handle
    msg = parse_message(msg)
  File "/opt/odoo/myaddons/oejia_wx/ext_libs/wechatpy/enterprise/parser.py", line 15, in parse_message
    message_type = message['MsgType'].lower()
KeyError: u'MsgType'
2016-11-30 07:49:15,468 16762 INFO mengzhicheng_pe werkzeug: 127.0.0.1 - - [30/Nov/2016 07:49:15] "GET /im_livechat/support/mengzhicheng_pe/2 HTTP/1.0" 200 -
```

**Comment by JoneXiong** [comment]
更新最新版本，odoo端的回复请参考企业版的功能
