### ISSUE TITLE
合并客户/Partner出现问题 relation "wx_menu_item_base" does not exist

### ISSUE THREAD

**Issue by skygunner** [JoneXiong/oejia_wx#5]
odoo 8,
合并客户，会出现以下错误：

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 576, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 309, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 805, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 405, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/crm/base_partner_merge.py", line 743, in merge_cb
    self._merge(cr, uid, partner_ids, this.dst_partner_id, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/misc.py", line 1145, in deco
    return func(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/crm/base_partner_merge.py", line 328, in _merge
    call_it(self._update_reference_fields)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/crm/base_partner_merge.py", line 325, in <lambda>
    context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/crm/base_partner_merge.py", line 260, in _update_reference_fields
    model_ids = proxy_model.search(cr, openerp.SUPERUSER_ID, domain, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 1646, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 4692, in _search
    cr.execute(query_str, where_clause_params)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "wx_menu_item_base" does not exist
LINE 1: SELECT "wx_menu_item_base".id FROM "wx_menu_item_base" WHERE...
                                           ^

**Comment by JoneXiong** [comment]
更新最新版本
