### ISSUE TITLE
设置－翻译－同步术语的时候出现SyntaxError

### ISSUE THREAD

**Issue by glovebx** [JoneXiong/oejia_wx#6]
SyntaxError: python refuses to compile code with both a UTF8 byte-order-mark and a magic encoding comment
2016-05-04 13:04:37,586 2003 ERROR newyui openerp.tools.translate: Failed to extract terms from /Users/glovebx/Dev/projects/python/odoo/addons/oejia_wx/ext_libs/werobot/robot.py
Traceback (most recent call last):
  File "/Users/glovebx/Dev/projects/python/odoo/openerp/tools/translate.py", line 886, in babel_extract_terms
    keywords=extract_keywords):
  File "/Library/Python/2.7/site-packages/babel/messages/extract.py", line 267, in extract
    for lineno, funcname, messages, comments in results:
  File "/Library/Python/2.7/site-packages/babel/messages/extract.py", line 351, in extract_python
    encoding = parse_encoding(fileobj) or options.get('encoding', 'iso-8859-1')
  File "/Library/Python/2.7/site-packages/babel/util.py", line 81, in parse_encoding
    "python refuses to compile code with both a UTF8 "
SyntaxError: python refuses to compile code with both a UTF8 byte-order-mark and a magic encoding comment

**Comment by JoneXiong** [comment]
无法重现
