### ISSUE TITLE
odoo 8配置企业号失败

### ISSUE THREAD

**Issue by tangramor** [JoneXiong/oejia_wx#9]
创建微信企业号应用，配置token与key时
微信企业号报：请求URL失败，HTTP返回码500

odoo系统后台日志：
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1297, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1271, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1444, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/addons/crm/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/opt/odoo/addons/website/models/ir_http.py", line 148, in _dispatch
    resp = super(ir_http, self)._dispatch()
  File "/opt/odoo/openerp/addons/base/ir/ir_http.py", line 175, in _dispatch
    return self._handle_exception(e)
  File "/opt/odoo/addons/website/models/ir_http.py", line 196, in _handle_exception
    return super(ir_http, self)._handle_exception(exception)
  File "/opt/odoo/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 673, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/openerp/http.py", line 691, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/myaddons/oejia_wx/controllers/wx_handler.py", line 60, in handle
    echo_str
  File "/opt/odoo/myaddons/oejia_wx/ext_libs/wechatpy/enterprise/crypto.py", line 28, in check_signature
    PrpCrypto
  File "/opt/odoo/myaddons/oejia_wx/ext_libs/wechatpy/crypto/__init__.py", line 56, in _check_signature
    pc = crypto_class(self.key)
  File "/opt/odoo/myaddons/oejia_wx/ext_libs/wechatpy/crypto/base.py", line 22, in __init__
    self.cipher = WeChatCipher(key)
  File "/opt/odoo/myaddons/oejia_wx/ext_libs/wechatpy/crypto/cryptography.py", line 10, in __init__
    backend = default_backend()
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
AttributeError: 'EntryPoint' object has no attribute 'resolve'

**Comment by tangramor** [comment]
fixed by upgrade setuptools:

sudo pip install --upgrade setuptools
